const peoples = [
  { name: "Aarav", age: 16 },
  { name: "Vivaan", age: 21 },
  { name: "Aditya", age: 17 },
  { name: "Rohan", age: 25 },
  { name: "Arjun", age: 18 },
  { name: "Kabir", age: 15 },
  { name: "Rahul", age: 30 },
  { name: "Karan", age: 19 },
  { name: "Yash", age: 14 },
  { name: "Aman", age: 22 },
  { name: "Riya", age: 17 },
  { name: "Ananya", age: 24 },
  { name: "Priya", age: 16 },
  { name: "Sneha", age: 20 },
  { name: "Neha", age: 13 },
  { name: "Pooja", age: 28 },
  { name: "Rohit", age: 18 },
  { name: "Vikram", age: 35 },
  { name: "Ishaan", age: 17 },
  { name: "Meera", age: 23 },
  { name: "Sahil", age: 16 },
  { name: "Nikhil", age: 27 },
  { name: "Simran", age: 19 },
  { name: "Ankit", age: 15 },
  { name: "Tanya", age: 31 },
  { name: "Varun", age: 17 },
  { name: "Deepak", age: 26 },
  { name: "Kavya", age: 18 },
  { name: "Manish", age: 14 },
  { name: "Shreya", age: 21 },
];
export default peoples;
